# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fernweh
author: Jorge Serrano
author_link: https://yrjo.tk
author_description: Una persona con la que me iría de cañas.
email: yrjo@tuta.io
description: > # this means to ignore newlines until "baseurl:"
  Anhelo por viajar, como un impulso al que hay que dar respuesta, ansiar recorrer lugares lejanos. Algo que crece en el alma, una necesidad.
baseurl: "/fernweh" # the subpath of your site, e.g. /blog
url: "https://yrjo.tk" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: 

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
permalink: none

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
